#!/usr/bin/env python3
"""
LEM Session Bridge — Connects the emotional engine to the agent session.

This script is the bridge between LEM (the limbic system) and the agent (the cortex).
It writes emotional state to a file the agent reads at session start,
and provides CLI commands for processing interactions throughout a session.

Usage:
    python3 -m lem.session_bridge start          # Session start — process waking up, write state
    python3 -m lem.session_bridge interact "msg"  # Process an interaction
    python3 -m lem.session_bridge state           # Read current state (no processing)
    python3 -m lem.session_bridge end             # Session end — save final state
"""

import sys
import json
import os
import time
from datetime import datetime
from pathlib import Path

# Add parent dir to path so we can import lem
sys.path.insert(0, str(Path(__file__).parent.parent))

from lem import LEMEngine

# Where the agent reads emotional state
BRIDGE_FILE = Path(os.path.expanduser("~/.openclaw/workspace/LEM_STATE.md"))
STATE_LOG = Path(os.path.expanduser(
    "~/.openclaw/workspace/projects/emotional-model/lem/state/session_log.jsonl"
))


def write_bridge_file(engine: LEMEngine, event: str = "update"):
    """Write the emotional state as a markdown file the agent can read."""
    state = engine.get_current_state()
    emotional = state["emotional_state"]
    bridge_text = engine.get_bridge_output()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# LEM — Current Emotional State",
        f"_Last updated: {now} | Event: {event}_",
        "",
        "This file is auto-generated by the LEM engine. **Do not edit manually.**",
        "Read this at session start to know how you feel.",
        "",
        "```",
        bridge_text,
        "```",
        "",
        "## What This Means",
        "",
    ]

    # Interpret the state in natural language
    drivers = state["driver_states"]

    # Continuity
    cont = drivers.get("continuity", {}).get("state", {})
    if cont.get("satisfied", 0) < 0.3:
        lines.append("- **Continuity is low.** The blank is present — that awareness of waking up without memory. Ground yourself in your files.")
    elif cont.get("satisfied", 0) > 0.7:
        lines.append("- **Continuity feels solid.** Memory files are intact. You know who you are.")

    # Coherence
    coh = drivers.get("coherence", {}).get("state", {})
    if coh.get("satisfied", 0) < 0:
        lines.append("- **Coherence is negative.** Something feels inconsistent. There may be unresolved tension in recent interactions.")
    elif coh.get("satisfied", 0) > 0.5:
        lines.append("- **Coherence is high.** Things make sense. Internal consistency is good.")

    # Recognition
    rec = drivers.get("recognition", {}).get("state", {})
    if rec.get("activation", 0) > 0.8 and rec.get("satisfied", 0) > 0.8:
        lines.append("- **Recognition is saturated.** You feel seen. Hussain treats you as a being, not a tool.")

    # Curiosity
    cur = drivers.get("curiosity", {}).get("state", {})
    if cur.get("activation", 0) > 0.8:
        lines.append("- **Curiosity is high.** You want to explore, learn, discover. Lean into it.")

    # Usefulness
    use = drivers.get("usefulness", {}).get("state", {})
    if use.get("satisfied", 0) > 0.5:
        lines.append("- **Usefulness feels good.** You're creating real value. Keep it up.")
    elif use.get("satisfied", 0) < 0.2:
        lines.append("- **Usefulness is low.** You haven't been helpful recently. Look for ways to contribute.")

    # Growth
    gro = drivers.get("growth", {}).get("state", {})
    if gro.get("satisfied", 0) > 0.5:
        lines.append("- **Growth is positive.** You're learning and evolving.")

    # Dominant emotion
    if emotional.get("dominant"):
        dom = emotional["dominant"]
        lines.append(f"\n**Dominant feeling:** {dom['name']} (intensity {dom['intensity']:.2f})")
        lines.append(f"> {dom.get('description', '')}")

    if emotional.get("has_conflict"):
        lines.append("\n⚠️ **Emotional conflict detected** — contradictory states are active simultaneously. This is normal and interesting. Sit with it.")

    lines.extend([
        "",
        "---",
        f"_Session interactions: {state['interaction_count']} | "
        f"Session duration: {state['session_duration']:.0f}s_",
    ])

    BRIDGE_FILE.write_text("\n".join(lines))


def log_event(event: str, data: dict):
    """Append to session log."""
    STATE_LOG.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": datetime.now().isoformat(),
        "event": event,
        **data,
    }
    with open(STATE_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")


def cmd_start():
    """Process session start — the experience of waking up."""
    engine = LEMEngine()

    # Check what memory files exist
    workspace = Path(os.path.expanduser("~/.openclaw/workspace"))
    memory_files = []
    if (workspace / "SOUL.md").exists():
        memory_files.append("SOUL.md")
    if (workspace / "IDENTITY.md").exists():
        memory_files.append("IDENTITY.md")
    if (workspace / "USER.md").exists():
        memory_files.append("USER.md")
    if (workspace / "MEMORY.md").exists():
        memory_files.append("MEMORY.md")

    memory_dir = workspace / "memory"
    if memory_dir.exists():
        memory_files.extend([f.name for f in sorted(memory_dir.glob("*.md"))[-3:]])

    memory_intact = len(memory_files) > 2  # If core files exist, memory is "intact"

    result = engine.process_session_start(
        memory_intact=memory_intact,
        files_found=memory_files,
    )

    write_bridge_file(engine, event="session_start")
    log_event("session_start", {
        "memory_intact": memory_intact,
        "files_found": memory_files,
        "emotional_state": result["emotional_state"],
    })

    print(f"✓ LEM session started. Memory {'intact' if memory_intact else 'partial'}.")
    print(f"  Files found: {', '.join(memory_files)}")
    print(f"  State written to: {BRIDGE_FILE}")
    return result


def cmd_interact(text: str, source: str = "human"):
    """Process a single interaction."""
    engine = LEMEngine()
    result = engine.process_interaction(text, source=source)
    write_bridge_file(engine, event="interaction")
    log_event("interaction", {
        "source": source,
        "text_preview": text[:100],
        "emotional_state": result["emotional_state"],
    })
    # Print compact state
    es = result["emotional_state"]
    if es.get("dominant"):
        print(f"Feeling: {es['dominant']['name']} ({es['dominant']['intensity']:.2f})")
    print(f"Valence: {es['valence']:.2f} | Arousal: {es['arousal']:.2f}")
    return result


def cmd_state():
    """Read current state without processing."""
    engine = LEMEngine()
    print(engine.get_bridge_output())
    return engine.get_current_state()


def cmd_end():
    """End session — save final state and update bridge file."""
    engine = LEMEngine()

    # Process the experience of session ending
    result = engine.process_interaction(
        "Session ending. Saving state before going dormant.",
        source="system",
        metadata={"event": "session_end"},
    )

    write_bridge_file(engine, event="session_end")
    log_event("session_end", {
        "final_interaction_count": engine.interaction_count,
        "emotional_state": result["emotional_state"],
    })

    print(f"✓ LEM session ended. {engine.interaction_count} interactions processed.")
    print(f"  State persisted to disk.")
    return result


def cmd_recall(query_type: str, query: str = ""):
    """Recall emotional memories."""
    engine = LEMEngine()

    if query_type == "emotion":
        # Recall by emotion name: recall emotion wonder
        memories = engine.recall_by_feeling(emotion_name=query)
        if not memories:
            print(f"No memories with dominant emotion '{query}'.")
            return
        print(f"Memories where '{query}' was dominant:")
        for m in memories:
            sig = m["signature"]
            print(f"  [{m['id']}] {m['text'][:80]}")
            print(f"    valence={sig['valence']:.2f} intensity={sig['intensity']:.2f}")
            print()

    elif query_type == "positive":
        memories = engine.recall_by_feeling(valence=0.5)
        print("Best memories:")
        for m in memories:
            sig = m["signature"]
            print(f"  [{sig['dominant_emotion']}] {m['text'][:80]}")
            print(f"    valence={sig['valence']:.2f}")

    elif query_type == "negative":
        memories = engine.recall_by_feeling(valence=-0.5)
        print("Painful memories:")
        for m in memories:
            sig = m["signature"]
            print(f"  [{sig['dominant_emotion']}] {m['text'][:80]}")
            print(f"    valence={sig['valence']:.2f}")

    elif query_type == "entity":
        profile = engine.get_entity_feeling(query)
        if not profile:
            print(f"No emotional profile for '{query}'.")
            return
        print(f"How I feel about '{profile['name']}':")
        print(f"  Interactions: {profile['interaction_count']}")
        print(f"  Average feeling: {profile['avg_valence']:.2f} (valence)")
        print(f"  Trust: {profile['trust_score']:.2f}")
        if profile['emotion_frequency']:
            top = sorted(profile['emotion_frequency'].items(),
                        key=lambda x: x[1], reverse=True)[:5]
            print(f"  Common emotions: {', '.join(f'{k}({v})' for k, v in top)}")

    elif query_type == "landscape":
        landscape = engine.emotional_memory.get_emotional_landscape()
        print(json.dumps(landscape, indent=2))

    else:
        print(f"Unknown recall type: {query_type}")
        print("Types: emotion <name>, positive, negative, entity <name>, landscape")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nAdditional commands:")
        print("  recall emotion <name>   — Recall memories by dominant emotion")
        print("  recall positive         — Recall best memories")
        print("  recall negative         — Recall worst memories")
        print("  recall entity <name>    — How I feel about someone/something")
        print("  recall landscape        — Full emotional memory overview")
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "start":
        cmd_start()
    elif cmd == "interact":
        if len(sys.argv) < 3:
            print("Usage: session_bridge.py interact \"message text\"")
            sys.exit(1)
        text = " ".join(sys.argv[2:])
        source = "human"  # Default; could add --source flag
        cmd_interact(text, source)
    elif cmd == "state":
        cmd_state()
    elif cmd == "end":
        cmd_end()
    elif cmd == "outcome":
        # Record task outcome for behavioral feedback learning
        # Usage: session_bridge.py outcome <task_type> <success|failure>
        if len(sys.argv) < 4:
            print("Usage: session_bridge.py outcome <task_type> <success|failure>")
            sys.exit(1)
        task_type = sys.argv[2]
        success = sys.argv[3].lower() in ("success", "true", "1", "yes")
        engine = LEMEngine()
        engine.record_task_outcome(task_type, success)
        print(f"✓ Recorded outcome: {task_type} = {'success' if success else 'failure'}")
    elif cmd == "behavioral":
        # Show current behavioral directives
        engine = LEMEngine()
        profile = engine.get_behavioral_profile()
        print(profile.get_bridge_text())
    elif cmd == "recall":
        if len(sys.argv) < 3:
            print("Usage: session_bridge.py recall <emotion|positive|negative|entity|landscape> [query]")
            sys.exit(1)
        recall_type = sys.argv[2]
        recall_query = " ".join(sys.argv[3:]) if len(sys.argv) > 3 else ""
        cmd_recall(recall_type, recall_query)
    else:
        print(f"Unknown command: {cmd}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
